language: python
python: '3.6'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest
script:
  - ls -la
deploy:
  provider: pypi
  user: devopshq
  password:
    secure: "GlV1bHTc0yPbkgVha9ABg0UyNk2QEI2lB/G0EQBM2zwD3tCKU3B0Xw9vLDMNg5MRqbXnPL43TxShxJfeIX2Rs/v9PH4XLun764+tbY2lm7AefVG1GNg7E7W3cYmeTNL9sSGTwmrqA/YRm59jA718Hqlv7Vulp7EaSPvj2QuzdO24DI4hvuiC+29dBxWeQ9JJbN/0UT3WPqyd2IFzJagT3wbBkzwdbMA/79wSZzirsZoOsUPue6vu81duJZOD3g3dChuruBmn/ftjcm/Kex9JN711Pois1H4Sf19r9JywH+9M6xdLjmOBRzPz/vv0MD7QX+OtnkgxKiY0RKc7P+MUFI9OKd4mM8Vl9Rp6Y3EHb5Tr6NoP/kV0i9RRvhFuhkTMvy29bIyOZeX9PWya80osMoSMVz328mrd4iIB7kIao1t2Vj4J2ublMhEz35XIyh2o3csVL5WZCFDAIHAJwIWBjoI1WJaKaOrYjPQLdEi79WvqRXM8SMUm4UJjzFgD6Nm5hG1w7AKf4LAxZkO4VMtIDALpNLweTnlHy3iCFtegQ5DD5Gv59iWt+lxYBMzvwjoKWtNIBDj4LpKEQI9R4oYfr1gk41ubruPGX060hoz0MAQ+dTpLuB0g6sS6/Vb/xD8MZKDWS8c8REQOi/s6a2mDRY4aVBFGK3YqzFn5QhMFe0s="
  distributions: bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true
after_script:
  - echo "Deploy to PyPI finished."
